Add @since annotations for tryError,withError,handleError,mapError
haskell/mtl pull request #143
Opened 2023-02-20 09:40 UTC by bezirg

2023-02-20 17:15 UTC, kozross approved these changes

2023-02-20 18:36 UTC, emilypi requested changes
I'd rather not change the comment style of the existing module and just keep with `-- |`. If you could revert the major changes and just add a `@since` entry to the existing comments, it'd makes this PR much smaller.

2023-02-20 23:38 UTC, emilypi approved these changes

2023-02-20 23:38 UTC, merged

2023-02-21 22:42 UTC, emilypi commented
Thanks @bezirg !